"""Dependency-free browser character creator for the v1.0.1 command workflow."""

CHARACTER_CREATOR_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RPG Engine Character Creator</title><style>
:root{font-family:system-ui,sans-serif;color-scheme:light dark}body{max-width:980px;margin:auto;padding:24px}fieldset{margin:18px 0;padding:16px;border:1px solid #888;border-radius:10px}label{display:block;margin:8px 0}input,select,textarea,button{font:inherit;padding:8px;box-sizing:border-box}input,select,textarea{width:100%}.grid,.abilities{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.status{white-space:pre-wrap;padding:12px;background:#8882;border-radius:8px}.muted{opacity:.75}button{cursor:pointer;margin:6px 6px 0 0}
</style></head><body>
<h1>Character Creator</h1><p>Build a fantasy character through the same authoritative commands used by every other client.</p>
<fieldset><legend>Campaign</legend><div class="grid"><label>Campaign ID<input id="campaign" value="my-campaign"></label><label>Seed<input id="seed" type="number" value="12345"></label></div><button id="createCampaign">Create campaign</button></fieldset>
<fieldset><legend>1. Identity</legend><div class="grid"><label>Name<input id="name" value="Arin"></label><label>Entity ID<input id="entity" value="arin"></label><label>Draft ID<input id="draft" value="arin-draft"></label><label>Pronouns<input id="pronouns"></label><label>Age<input id="age" type="number" min="0"></label></div><button id="begin">Begin character</button></fieldset>
<fieldset><legend>2. Race / Ancestry, Class & Background</legend><div class="grid"><label>Race / Ancestry<select id="ancestry"></select></label><label>Class<select id="classChoice"></select></label><label>Background<select id="background"></select></label><label>Starting location<select id="location"><option value="">No location</option></select></label></div><button id="saveChoices">Save choices</button></fieldset>
<fieldset><legend>3. Ability Scores</legend><label>Method<select id="method"><option value="standard_array">Standard array</option><option value="point_buy">27-point buy</option><option value="rolled">Roll 4d6, drop lowest</option><option value="manual">Manual</option></select></label><button id="generate">Generate pool</button><span id="pool" class="muted"></span><div class="abilities" id="abilities"></div><p id="pointBuy" class="muted"></p><button id="assign">Assign scores</button></fieldset>
<fieldset><legend>4. Describe Your Character</legend><label>Appearance<textarea id="appearance" rows="3"></textarea></label><label>Personality<textarea id="personality" rows="3"></textarea></label><div class="grid"><label>Ideals<textarea id="ideals"></textarea></label><label>Bonds<textarea id="bonds"></textarea></label><label>Flaws<textarea id="flaws"></textarea></label></div><label>Backstory<textarea id="backstory" rows="5"></textarea></label><label>Goals<textarea id="goals" rows="3"></textarea></label><label>Notes<textarea id="notes" rows="3"></textarea></label><button id="saveDescription">Save description</button></fieldset>
<fieldset><legend>5. Finalize</legend><p>Finalization derives HP, AC, speed, inventory, resources and tags into a normal engine Entity.</p><button id="finalize">Finalize character</button></fieldset>
<h2>Status</h2><div id="status" class="status" aria-live="polite">Loading catalog…</div>
<script>
const abilities=['strength','dexterity','constitution','intelligence','wisdom','charisma'];let catalog;const $=id=>document.getElementById(id);const show=x=>$('status').textContent=typeof x==='string'?x:JSON.stringify(x,null,2);
async function request(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||JSON.stringify(data));return data}
const commandUrl=()=>`/api/v1/campaigns/${encodeURIComponent($('campaign').value)}/commands`;async function send(command){const result=await request(commandUrl(),{method:'POST',body:JSON.stringify(command)});show(result);return result}
function fill(select,items){select.innerHTML='';for(const item of items){const o=document.createElement('option');o.value=item.id;o.textContent=item.name;select.appendChild(o)}}
function renderAbilities(){for(const a of abilities){const l=document.createElement('label');l.textContent=a[0].toUpperCase()+a.slice(1);const i=document.createElement('input');i.type='number';i.id=`ability-${a}`;i.value='10';i.addEventListener('input',updatePointBuy);l.appendChild(i);$('abilities').appendChild(l)}}
const scores=()=>Object.fromEntries(abilities.map(a=>[a,Number($(`ability-${a}`).value)]));function updatePointBuy(){if(!catalog||$('method').value!=='point_buy'){$('pointBuy').textContent='';return}let cost=0,ok=true;for(const v of Object.values(scores())){const c=catalog.point_buy_costs[String(v)];if(c===undefined)ok=false;else cost+=c}$('pointBuy').textContent=ok?`Point-buy: ${cost}/${catalog.point_buy_budget} used; ${catalog.point_buy_budget-cost} remaining`:'Point-buy scores must be 8–15'}
function description(){const age=$('age').value;return{pronouns:$('pronouns').value,age:age===''?null:Number(age),appearance:$('appearance').value,personality:$('personality').value,ideals:$('ideals').value,bonds:$('bonds').value,flaws:$('flaws').value,backstory:$('backstory').value,goals:$('goals').value,notes:$('notes').value}}
async function load(){catalog=await request('/api/v1/character-creation/catalog');fill($('ancestry'),catalog.ancestries);fill($('classChoice'),catalog.classes);fill($('background'),catalog.backgrounds);for(const item of catalog.locations){const o=document.createElement('option');o.value=item.id;o.textContent=item.name;$('location').appendChild(o)}renderAbilities();show('Catalog loaded. Create a campaign to begin.')}
$('createCampaign').addEventListener('click',()=>request('/api/v1/campaigns',{method:'POST',body:JSON.stringify({seed:Number($('seed').value),campaign_id:$('campaign').value})}).then(show).catch(e=>show(e.message)));
$('begin').addEventListener('click',()=>send({type:'begin_character_creation',draft_id:$('draft').value,entity_id:$('entity').value,name:$('name').value}).catch(e=>show(e.message)));
$('saveChoices').addEventListener('click',()=>send({type:'update_character_draft',draft_id:$('draft').value,name:$('name').value,ancestry_id:$('ancestry').value,class_id:$('classChoice').value,background_id:$('background').value}).catch(e=>show(e.message)));
$('saveDescription').addEventListener('click',()=>send({type:'update_character_draft',draft_id:$('draft').value,description:description()}).catch(e=>show(e.message)));
$('method').addEventListener('change',updatePointBuy);
$('generate').addEventListener('click',async()=>{try{const method=$('method').value;if(!['standard_array','rolled'].includes(method))throw new Error('Generate is for standard-array or rolled scores.');const result=await send({type:'generate_character_abilities',draft_id:$('draft').value,method});const ev=result.events.find(e=>e.type==='character_abilities_generated');if(ev){$('pool').textContent=`Pool: ${ev.score_pool.join(', ')}`;ev.score_pool.forEach((v,i)=>{$(`ability-${abilities[i]}`).value=v});updatePointBuy()}}catch(e){show(e.message)}});
$('assign').addEventListener('click',()=>send({type:'assign_character_abilities',draft_id:$('draft').value,method:$('method').value,scores:scores()}).catch(e=>show(e.message)));
$('finalize').addEventListener('click',()=>send({type:'finalize_character',draft_id:$('draft').value,start_location_id:$('location').value||null}).catch(e=>show(e.message)));load().catch(e=>show(e.message));
</script></body></html>'''
